\c economundi;

insert into usuario (email, nome, sobrenome, senha, data_nasc, perfil_economico) values ("Alexandresilva58@gmail.com", "Alexandre", "Ribeiro", "123456", "1991-07-01", "Moderado-agressivo");
insert into usuario (email, nome, sobrenome, senha, data_nasc, perfil_economico) values ("joaovitorteixeira10.JVT@gmail.com", "João Vitor", "Teixeira", "123456", "1999-03-09", "Conservador");
insert into usuario (email, nome, sobrenome, senha, data_nasc, perfil_economico) values ("dev.mateusbarbosa@gmail.com", "Mateus José", "Barbosa", "123456", "1999-03-10", "Moderado");

insert into palavra (nome, descricao) values ('INVESTIMENTO', 'Emprego da poupança em atividade produtiva, com o objetivo de auferir ganhos a médio ou longo prazo. É utilizado, também, para designar a aplicação de recursos em algum tipo de ativo financeiro.');
insert into palavra (nome, descricao) values ('BOLSA DE VALORES', 'Lugar onde se negociam títulos e valores mobiliários (sobretudo ações, opções, direitos e debêntures). A BM&FBOVESPA é a principal instituição brasileira de intermediação para operações do mercado de capitais e a única bolsa de valores, mercadorias e futuros em operação no Brasil.');
insert into palavra (nome, descricao) values ('GARANTIA', 'O termo garantia, ou colateral, se refere aos itens usados por uma empresa ou indivíduo para sustentar o crédito quando levanta um financiamento. Assim, a garantia de um empréstimo pode ser qualquer ativo sobre o qual o credor (quem emprestou o dinheiro) tem um direito legal, que pode ser exercido caso o tomador do empréstimo não cumpra alguma das cláusulas do contrato.');
insert into palavra (nome, descricao) values ('VOLATILIDADE', 'Indica o grau médio de variação da cotação de um título ou determinado mercado de subir ou cair intensamente em um curto período de tempo. A relação da volatilidade de uma ação em relação à volatilidade do mercado acionário como um todo pode ser medida através do seu coeficiente beta. Quando se afirma que uma aplicação é extremamente volátil, entende-se que esta aplicação está sujeita a fortes oscilações, o que pode ser decorrência das perspectivas para a companhia, falta de liquidez (bastante comum entre algumas ações no Brasil), ou outras razões.');
insert into palavra (nome, descricao) values ('MARCA', 'Determina todo sinal visualmente perceptível, que identifica e distingue produtos e serviços de outros análogos, de procedência diversa, e certifica sua conformidade com as normas e especificações técnicas pertinentes. O registro de uma marca é obtido, no Brasil, por intermédio do INPI - Instituto Nacional da Propriedade Industrial, que pode ser acessado pelo endereço eletrônico (www.inpi.gov.br).');
insert into palavra (nome, descricao) values ('FORNECEDOR', 'Qualquer organização que forneça bens e serviços, sendo que o uso destes bens e serviços pode acontecer em qualquer estágio da produção. Podem ser incluídos como fornecedores os distribuidores, revendedores, bem como os indivíduos que suprem a empresa com materiais e componentes.');
insert into palavra (nome, descricao) values ('BNDES', 'Sigla que designa o Banco Nacional de Desenvolvimento Econômico Social, que é o órgão governamental responsável pela implementação de políticas de investimento empresarial de longo prazo. Dentre as principais responsabilidades do BNDES estão: impulsionar o crescimento da economia, atuando como instituição de fomento; fortalecer o empresariado nacional; promover a diversificação e o crescimento das exportações; criar pólos de produção para diminuir possíveis desequilíbrios regionais. As atividades de fomento da instituição são conduzidas através de programas especiais como, por exemplo, o Finame, Finem e Finac.');
insert into palavra (nome, descricao) values ('AÇÃO', 'Valor mobiliário emitido pelas sociedades anônimas, representando a menor fração do capital destas empresas. As empresas emitem ações para aumentar o capital social, e os recursos levantados podem ser utilizados para vários fins, sobretudo futuros investimentos');
insert into palavra (nome, descricao) values ('PIB', 'Sigla que significa Produto Interno Bruto. Ver definição em PRODUTO INTERNO BRUTO.');
insert into palavra (nome, descricao) values ('PREGÃO', 'Intervalo de tempo durante o qual papéis listados em uma bolsa de valores são negociados, diretamente na sala de negociações e/ou pelo sistema de negociação eletrônica.');