/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.backend.economundi.payload;

import com.backend.economundi.database.dao.entity.NewsLetterDto;
import com.backend.economundi.database.dao.entity.UserEntity;
import com.backend.economundi.database.dao.entity.WordEntity;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 *
 * @author Alexandre
 */
@Component
public class EmailTemplates {

    public String getTemplateSign(String name) {
        String template = "<!DOCTYPE html\n"
                + "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "    <title>Economundi</title>\n"
                + "    <!-- Designed by https://github.com/kaytcat -->\n"
                + "    <!-- Robot header image designed by Freepik.com -->\n"
                + "\n"
                + "    <style type=\"text/css\">\n"
                + "        @import url(http://fonts.googleapis.com/css?family=Droid+Sans);\n"
                + "\n"
                + "        /* Take care of image borders and formatting */\n"
                + "\n"
                + "        img {\n"
                + "            max-width: 600px;\n"
                + "            outline: none;\n"
                + "            text-decoration: none;\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "            border: 0;\n"
                + "            outline: none;\n"
                + "            color: #bbbbbb;\n"
                + "        }\n"
                + "\n"
                + "        a img {\n"
                + "            border: none;\n"
                + "        }\n"
                + "\n"
                + "        /* General styling */\n"
                + "\n"
                + "        td,\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3 {\n"
                + "            font-family: Helvetica, Arial, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            -webkit-font-smoothing: antialiased;\n"
                + "            -webkit-text-size-adjust: none;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            color: #37302d;\n"
                + "            background: #ffffff;\n"
                + "            font-size: 16px;\n"
                + "        }\n"
                + "\n"
                + "        table {\n"
                + "            border-collapse: collapse !important;\n"
                + "        }\n"
                + "\n"
                + "        .headline {\n"
                + "            color: #ffffff;\n"
                + "            font-size: 36px;\n"
                + "        }\n"
                + "\n"
                + "        .force-full-width {\n"
                + "            width: 100% !important;\n"
                + "        }\n"
                + "\n"
                + "        .force-width-80 {\n"
                + "            width: 80% !important;\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"screen\">\n"
                + "        @media screen {\n"
                + "\n"
                + "            /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/\n"
                + "            td,\n"
                + "            h1,\n"
                + "            h2,\n"
                + "            h3 {\n"
                + "                font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"only screen and (max-width: 480px)\">\n"
                + "        /* Mobile styles */\n"
                + "        @media only screen and (max-width: 480px) {\n"
                + "\n"
                + "            table[class=\"w320\"] {\n"
                + "                width: 320px !important;\n"
                + "            }\n"
                + "\n"
                + "            td[class=\"mobile-block\"] {\n"
                + "                width: 100% !important;\n"
                + "                display: block !important;\n"
                + "            }\n"
                + "\n"
                + "\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"body\" style=\"padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\"\n"
                + "    bgcolor=\"#ffffff\">\n"
                + "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\" height=\"100%\">\n"
                + "        <tr>\n"
                + "            <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\" width=\"100%\">\n"
                + "                <center>\n"
                + "                    <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">\n"
                + "                        <tr>\n"
                + "                            <td align=\"center\" valign=\"top\">\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    style=\"margin:0 auto;\">\n"
                + "                                    <tr>\n"
                + "                                        <td style=\"font-size: 30px; text-align:center;\">\n"
                + "                                            Portal EconoMundi\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    bgcolor=\"#4dbfbf\">\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <br>\n"
                + "                                            <img src=\"https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf\"\n"
                + "                                                width=\"224\" height=\"240\" alt=\"robot picture\">\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td class=\"headline\">\n"
                + "                                            " + name + " Seu Cadastro Foi Realizado Com Sucesso!\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "\n"
                + "                                            <center>\n"
                + "                                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\"\n"
                + "                                                    width=\"60%\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td style=\"color:#187272;\">\n"
                + "                                                            <br>\n"
                + "                                                            Obrigado por se Cadastrar.\n"
                + "                                                            <br>\n"
                + "                                                            <br>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "                                            </center>\n"
                + "\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <div>\n"
                + "\n"
                + "                                                <a href=\"http://localhost:3000/noticias\"\n"
                + "                                                    style=\"background-color:#178f8f;border-radius:4px;color:#ffffff;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:50px;text-align:center;text-decoration:none;width:200px;-webkit-text-size-adjust:none;\">\n"
                + "                                                    Voltar ao Portal</a>\n"
                + "\n"
                + "                                            </div>\n"
                + "                                            <br>\n"
                + "                                            <br>\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                            </td>\n"
                + "                        </tr>\n"
                + "                    </table>\n"
                + "                </center>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

    public String getTemplateRecovery(UserEntity user) {
        String template = "<!DOCTYPE html\n"
                + "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "    <title>Economundi</title>\n"
                + "    <!-- Designed by https://github.com/kaytcat -->\n"
                + "    <!-- Robot header image designed by Freepik.com -->\n"
                + "\n"
                + "    <style type=\"text/css\">\n"
                + "        @import url(http://fonts.googleapis.com/css?family=Droid+Sans);\n"
                + "\n"
                + "        /* Take care of image borders and formatting */\n"
                + "\n"
                + "        img {\n"
                + "            max-width: 600px;\n"
                + "            outline: none;\n"
                + "            text-decoration: none;\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "            border: 0;\n"
                + "            outline: none;\n"
                + "            color: #bbbbbb;\n"
                + "        }\n"
                + "\n"
                + "        a img {\n"
                + "            border: none;\n"
                + "        }\n"
                + "\n"
                + "        /* General styling */\n"
                + "\n"
                + "        td,\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3 {\n"
                + "            font-family: Helvetica, Arial, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            -webkit-font-smoothing: antialiased;\n"
                + "            -webkit-text-size-adjust: none;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            color: #37302d;\n"
                + "            background: #ffffff;\n"
                + "            font-size: 16px;\n"
                + "        }\n"
                + "\n"
                + "        table {\n"
                + "            border-collapse: collapse !important;\n"
                + "        }\n"
                + "\n"
                + "        .headline {\n"
                + "            color: #ffffff;\n"
                + "            font-size: 36px;\n"
                + "        }\n"
                + "\n"
                + "        .force-full-width {\n"
                + "            width: 100% !important;\n"
                + "        }\n"
                + "\n"
                + "        .force-width-80 {\n"
                + "            width: 80% !important;\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"screen\">\n"
                + "        @media screen {\n"
                + "\n"
                + "            /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/\n"
                + "            td,\n"
                + "            h1,\n"
                + "            h2,\n"
                + "            h3 {\n"
                + "                font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"only screen and (max-width: 480px)\">\n"
                + "        /* Mobile styles */\n"
                + "        @media only screen and (max-width: 480px) {\n"
                + "\n"
                + "            table[class=\"w320\"] {\n"
                + "                width: 320px !important;\n"
                + "            }\n"
                + "\n"
                + "            td[class=\"mobile-block\"] {\n"
                + "                width: 100% !important;\n"
                + "                display: block !important;\n"
                + "            }\n"
                + "\n"
                + "\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"body\" style=\"padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\"\n"
                + "    bgcolor=\"#ffffff\">\n"
                + "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\" height=\"100%\">\n"
                + "        <tr>\n"
                + "            <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\" width=\"100%\">\n"
                + "                <center>\n"
                + "                    <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">\n"
                + "                        <tr>\n"
                + "                            <td align=\"center\" valign=\"top\">\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    style=\"margin:0 auto;\">\n"
                + "                                    <tr>\n"
                + "                                        <td style=\"font-size: 30px; text-align:center;\">\n"
                + "                                            Portal EconoMundi\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    bgcolor=\"#4dbfbf\">\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <br>\n"
                + "                                            <img src=\"https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf\"\n"
                + "                                                width=\"224\" height=\"240\" alt=\"robot picture\">\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td class=\"headline\">\n"
                + "                                            " + user.getFirst_name() + " Clique no Botão Abaixo para redefinir sua Senha!\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "\n"
                + "                                            <center>\n"
                + "                                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\"\n"
                + "                                                    width=\"60%\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td style=\"color:#187272;\">\n"
                + "                                                            <br>\n"
                + "                                                            você será redirecionado a página de redefinição de senha.\n"
                + "                                                            <br>\n"
                + "                                                            <br>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "                                            </center>\n"
                + "\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <div>\n"
                + "\n"
                + "                                                <a href=\"http://localhost:3000/recovery?" + user.getEmailVerificationToken() + "\"\n"
                + "                                                    style=\"background-color:#178f8f;border-radius:4px;color:#ffffff;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:50px;text-align:center;text-decoration:none;width:200px;-webkit-text-size-adjust:none;\">\n"
                + "                                                    Redefinir Senha</a>\n"
                + "\n"
                + "                                            </div>\n"
                + "                                            <br>\n"
                + "                                            <br>\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n" + "\n"
                + "\n"
                + "\n"
                + "                            </td>\n"
                + "                        </tr>\n"
                + "                    </table>\n"
                + "                </center>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

    public String getNewsLetterTemplate(List<NewsLetterDto> newsLetterBrazilList, List<NewsLetterDto> newsLetterWorldList, List<WordEntity> wordList) {

        String template = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "  <style>\n"
                + "    :root {\n"
                + "      --blue: #007bff;\n"
                + "      --indigo: #6610f2;\n"
                + "      --purple: #6f42c1;\n"
                + "      --pink: #e83e8c;\n"
                + "      --red: #dc3545;\n"
                + "      --orange: #fd7e14;\n"
                + "      --yellow: #ffc107;\n"
                + "      --green: #28a745;\n"
                + "      --teal: #20c997;\n"
                + "      --cyan: #17a2b8;\n"
                + "      --white: #fff;\n"
                + "      --gray: #6c757d;\n"
                + "      --gray-dark: #343a40;\n"
                + "      --primary: #007bff;\n"
                + "      --secondary: #6c757d;\n"
                + "      --success: #28a745;\n"
                + "      --info: #17a2b8;\n"
                + "      --warning: #ffc107;\n"
                + "      --danger: #dc3545;\n"
                + "      --light: #f8f9fa;\n"
                + "      --dark: #343a40;\n"
                + "      --breakpoint-xs: 0;\n"
                + "      --breakpoint-sm: 576px;\n"
                + "      --breakpoint-md: 768px;\n"
                + "      --breakpoint-lg: 992px;\n"
                + "      --breakpoint-xl: 1200px;\n"
                + "      --font-family-sans-serif: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
                + "      --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
                + "    }\n"
                + "\n"
                + "    *,\n"
                + "    *::before,\n"
                + "    *::after {\n"
                + "      box-sizing: border-box;\n"
                + "    }\n"
                + "\n"
                + "    html {\n"
                + "      font-family: sans-serif;\n"
                + "      line-height: 1.15;\n"
                + "      -webkit-text-size-adjust: 100%;\n"
                + "      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n"
                + "    }\n"
                + "\n"
                + "    article,\n"
                + "    aside,\n"
                + "    figcaption,\n"
                + "    figure,\n"
                + "    footer,\n"
                + "    header,\n"
                + "    hgroup,\n"
                + "    main,\n"
                + "    nav,\n"
                + "    section {\n"
                + "      display: block;\n"
                + "    }\n"
                + "\n"
                + "    body {\n"
                + "      margin: 0;\n"
                + "      font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
                + "      font-size: 1rem;\n"
                + "      font-weight: 400;\n"
                + "      line-height: 1.5;\n"
                + "      color: #212529;\n"
                + "      text-align: left;\n"
                + "      background-color: #fff;\n"
                + "    }\n"
                + "\n"
                + "    [tabindex=\"-1\"]:focus {\n"
                + "      outline: 0 !important;\n"
                + "    }\n"
                + "\n"
                + "    hr {\n"
                + "      box-sizing: content-box;\n"
                + "      height: 0;\n"
                + "      overflow: visible;\n"
                + "    }\n"
                + "\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4,\n"
                + "    h5,\n"
                + "    h6 {\n"
                + "      margin-top: 0;\n"
                + "      margin-bottom: 0.5rem;\n"
                + "    }\n"
                + "\n"
                + "    p {\n"
                + "      margin-top: 0;\n"
                + "      margin-bottom: 1rem;\n"
                + "    }\n"
                + "\n"
                + "    abbr[title],\n"
                + "    abbr[data-original-title] {\n"
                + "      text-decoration: underline;\n"
                + "      -webkit-text-decoration: underline dotted;\n"
                + "      text-decoration: underline dotted;\n"
                + "      cursor: help;\n"
                + "      border-bottom: 0;\n"
                + "      -webkit-text-decoration-skip-ink: none;\n"
                + "      text-decoration-skip-ink: none;\n"
                + "    }\n"
                + "\n"
                + "    address {\n"
                + "      margin-bottom: 1rem;\n"
                + "      font-style: normal;\n"
                + "      line-height: inherit;\n"
                + "    }\n"
                + "\n"
                + "    ol,\n"
                + "    ul,\n"
                + "    dl {\n"
                + "      margin-top: 0;\n"
                + "      margin-bottom: 1rem;\n"
                + "    }\n"
                + "\n"
                + "    ol ol,\n"
                + "    ul ul,\n"
                + "    ol ul,\n"
                + "    ul ol {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    dt {\n"
                + "      font-weight: 700;\n"
                + "    }\n"
                + "\n"
                + "    dd {\n"
                + "      margin-bottom: .5rem;\n"
                + "      margin-left: 0;\n"
                + "    }\n"
                + "\n"
                + "    blockquote {\n"
                + "      margin: 0 0 1rem;\n"
                + "    }\n"
                + "\n"
                + "    b,\n"
                + "    strong {\n"
                + "      font-weight: bolder;\n"
                + "    }\n"
                + "\n"
                + "    small {\n"
                + "      font-size: 80%;\n"
                + "    }\n"
                + "\n"
                + "    sub,\n"
                + "    sup {\n"
                + "      position: relative;\n"
                + "      font-size: 75%;\n"
                + "      line-height: 0;\n"
                + "      vertical-align: baseline;\n"
                + "    }\n"
                + "\n"
                + "    sub {\n"
                + "      bottom: -.25em;\n"
                + "    }\n"
                + "\n"
                + "    sup {\n"
                + "      top: -.5em;\n"
                + "    }\n"
                + "\n"
                + "    a {\n"
                + "      color: #007bff;\n"
                + "      text-decoration: none;\n"
                + "      background-color: transparent;\n"
                + "    }\n"
                + "\n"
                + "    a:hover {\n"
                + "      color: #0056b3;\n"
                + "      text-decoration: underline;\n"
                + "    }\n"
                + "\n"
                + "    a:not([href]):not([tabindex]) {\n"
                + "      color: inherit;\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    a:not([href]):not([tabindex]):hover,\n"
                + "    a:not([href]):not([tabindex]):focus {\n"
                + "      color: inherit;\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    a:not([href]):not([tabindex]):focus {\n"
                + "      outline: 0;\n"
                + "    }\n"
                + "\n"
                + "    pre,\n"
                + "    code,\n"
                + "    kbd,\n"
                + "    samp {\n"
                + "      font-family: SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
                + "      font-size: 1em;\n"
                + "    }\n"
                + "\n"
                + "    pre {\n"
                + "      margin-top: 0;\n"
                + "      margin-bottom: 1rem;\n"
                + "      overflow: auto;\n"
                + "    }\n"
                + "\n"
                + "    figure {\n"
                + "      margin: 0 0 1rem;\n"
                + "    }\n"
                + "\n"
                + "    img {\n"
                + "      vertical-align: middle;\n"
                + "      border-style: none;\n"
                + "    }\n"
                + "\n"
                + "    svg {\n"
                + "      overflow: hidden;\n"
                + "      vertical-align: middle;\n"
                + "    }\n"
                + "\n"
                + "    table {\n"
                + "      border-collapse: collapse;\n"
                + "    }\n"
                + "\n"
                + "    caption {\n"
                + "      padding-top: 0.75rem;\n"
                + "      padding-bottom: 0.75rem;\n"
                + "      color: #6c757d;\n"
                + "      text-align: left;\n"
                + "      caption-side: bottom;\n"
                + "    }\n"
                + "\n"
                + "    th {\n"
                + "      text-align: inherit;\n"
                + "    }\n"
                + "\n"
                + "    label {\n"
                + "      display: inline-block;\n"
                + "      margin-bottom: 0.5rem;\n"
                + "    }\n"
                + "\n"
                + "    button {\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "\n"
                + "    button:focus {\n"
                + "      outline: 1px dotted;\n"
                + "      outline: 5px auto -webkit-focus-ring-color;\n"
                + "    }\n"
                + "\n"
                + "    input,\n"
                + "    button,\n"
                + "    select,\n"
                + "    optgroup,\n"
                + "    textarea {\n"
                + "      margin: 0;\n"
                + "      font-family: inherit;\n"
                + "      font-size: inherit;\n"
                + "      line-height: inherit;\n"
                + "    }\n"
                + "\n"
                + "    button,\n"
                + "    input {\n"
                + "      overflow: visible;\n"
                + "    }\n"
                + "\n"
                + "    button,\n"
                + "    select {\n"
                + "      text-transform: none;\n"
                + "    }\n"
                + "\n"
                + "    select {\n"
                + "      word-wrap: normal;\n"
                + "    }\n"
                + "\n"
                + "    button,\n"
                + "    [type=\"button\"],\n"
                + "    [type=\"reset\"],\n"
                + "    [type=\"submit\"] {\n"
                + "      -webkit-appearance: button;\n"
                + "    }\n"
                + "\n"
                + "    button:not(:disabled),\n"
                + "    [type=\"button\"]:not(:disabled),\n"
                + "    [type=\"reset\"]:not(:disabled),\n"
                + "    [type=\"submit\"]:not(:disabled) {\n"
                + "      cursor: pointer;\n"
                + "    }\n"
                + "\n"
                + "    button::-moz-focus-inner,\n"
                + "    [type=\"button\"]::-moz-focus-inner,\n"
                + "    [type=\"reset\"]::-moz-focus-inner,\n"
                + "    [type=\"submit\"]::-moz-focus-inner {\n"
                + "      padding: 0;\n"
                + "      border-style: none;\n"
                + "    }\n"
                + "\n"
                + "    input[type=\"radio\"],\n"
                + "    input[type=\"checkbox\"] {\n"
                + "      box-sizing: border-box;\n"
                + "      padding: 0;\n"
                + "    }\n"
                + "\n"
                + "    input[type=\"date\"],\n"
                + "    input[type=\"time\"],\n"
                + "    input[type=\"datetime-local\"],\n"
                + "    input[type=\"month\"] {\n"
                + "      -webkit-appearance: listbox;\n"
                + "    }\n"
                + "\n"
                + "    textarea {\n"
                + "      overflow: auto;\n"
                + "      resize: vertical;\n"
                + "    }\n"
                + "\n"
                + "    fieldset {\n"
                + "      min-width: 0;\n"
                + "      padding: 0;\n"
                + "      margin: 0;\n"
                + "      border: 0;\n"
                + "    }\n"
                + "\n"
                + "    legend {\n"
                + "      display: block;\n"
                + "      width: 100%;\n"
                + "      max-width: 100%;\n"
                + "      padding: 0;\n"
                + "      margin-bottom: .5rem;\n"
                + "      font-size: 1.5rem;\n"
                + "      line-height: inherit;\n"
                + "      color: inherit;\n"
                + "      white-space: normal;\n"
                + "    }\n"
                + "\n"
                + "    progress {\n"
                + "      vertical-align: baseline;\n"
                + "    }\n"
                + "\n"
                + "    [type=\"number\"]::-webkit-inner-spin-button,\n"
                + "    [type=\"number\"]::-webkit-outer-spin-button {\n"
                + "      height: auto;\n"
                + "    }\n"
                + "\n"
                + "    [type=\"search\"] {\n"
                + "      outline-offset: -2px;\n"
                + "      -webkit-appearance: none;\n"
                + "    }\n"
                + "\n"
                + "    [type=\"search\"]::-webkit-search-decoration {\n"
                + "      -webkit-appearance: none;\n"
                + "    }\n"
                + "\n"
                + "    ::-webkit-file-upload-button {\n"
                + "      font: inherit;\n"
                + "      -webkit-appearance: button;\n"
                + "    }\n"
                + "\n"
                + "    output {\n"
                + "      display: inline-block;\n"
                + "    }\n"
                + "\n"
                + "    summary {\n"
                + "      display: list-item;\n"
                + "      cursor: pointer;\n"
                + "    }\n"
                + "\n"
                + "    template {\n"
                + "      display: none;\n"
                + "    }\n"
                + "\n"
                + "    [hidden] {\n"
                + "      display: none !important;\n"
                + "    }\n"
                + "\n"
                + "    h1,\n"
                + "    h2,\n"
                + "    h3,\n"
                + "    h4,\n"
                + "    h5,\n"
                + "    h6,\n"
                + "    .h1,\n"
                + "    .h2,\n"
                + "    .h3,\n"
                + "    .h4,\n"
                + "    .h5,\n"
                + "    .h6 {\n"
                + "      margin-bottom: 0.5rem;\n"
                + "      font-weight: 500;\n"
                + "      line-height: 1.2;\n"
                + "    }\n"
                + "\n"
                + "    h1,\n"
                + "    .h1 {\n"
                + "      font-size: 2.5rem;\n"
                + "    }\n"
                + "\n"
                + "    h2,\n"
                + "    .h2 {\n"
                + "      font-size: 2rem;\n"
                + "    }\n"
                + "\n"
                + "    h3,\n"
                + "    .h3 {\n"
                + "      font-size: 1.75rem;\n"
                + "    }\n"
                + "\n"
                + "    h4,\n"
                + "    .h4 {\n"
                + "      font-size: 1.5rem;\n"
                + "    }\n"
                + "\n"
                + "    h5,\n"
                + "    .h5 {\n"
                + "      font-size: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    h6,\n"
                + "    .h6 {\n"
                + "      font-size: 1rem;\n"
                + "    }\n"
                + "\n"
                + "    .word {\n"
                + "      position: relative;\n"
                + "      align-content: center;\n"
                + "      left: 10%;\n"
                + "    }\n"
                + "\n"
                + "    .word-card {\n"
                + "      margin: 3px;\n"
                + "    }\n"
                + "\n"
                + "    a:hover {\n"
                + "      display: none;\n"
                + "    }\n"
                + "\n"
                + "    .container {\n"
                + "      width: 100%;\n"
                + "      padding-right: 15px;\n"
                + "      padding-left: 15px;\n"
                + "      margin-right: auto;\n"
                + "      margin-left: auto;\n"
                + "    }\n"
                + "\n"
                + "    @media (min-width: 576px) {\n"
                + "      .container {\n"
                + "        max-width: 540px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media (min-width: 768px) {\n"
                + "      .container {\n"
                + "        max-width: 720px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media (min-width: 992px) {\n"
                + "      .container {\n"
                + "        max-width: 960px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    @media (min-width: 1200px) {\n"
                + "      .container {\n"
                + "        max-width: 1140px;\n"
                + "      }\n"
                + "    }\n"
                + "\n"
                + "    .container-fluid {\n"
                + "      width: 100%;\n"
                + "      padding-right: 15px;\n"
                + "      padding-left: 15px;\n"
                + "      margin-right: auto;\n"
                + "      margin-left: auto;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    .row {\n"
                + "      display: -ms-flexbox;\n"
                + "      display: flex;\n"
                + "      -ms-flex-wrap: wrap;\n"
                + "      flex-wrap: wrap;\n"
                + "      margin-right: -15px;\n"
                + "      margin-left: -15px;\n"
                + "    }\n"
                + "\n"
                + "    .text-center {\n"
                + "      text-align: center !important;\n"
                + "    }\n"
                + "\n"
                + "    .card {\n"
                + "      position: relative;\n"
                + "      display: -ms-flexbox;\n"
                + "      display: flex;\n"
                + "      -ms-flex-direction: column;\n"
                + "      flex-direction: column;\n"
                + "      min-width: 0;\n"
                + "      word-wrap: break-word;\n"
                + "      background-color: #fff;\n"
                + "      background-clip: border-box;\n"
                + "      border: 1px solid rgba(0, 0, 0, 0.125);\n"
                + "      border-radius: 0.25rem;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    .card-header {\n"
                + "      padding: 0.75rem 1.25rem;\n"
                + "      margin-bottom: 0;\n"
                + "      background-color: rgba(0, 0, 0, 0.03);\n"
                + "      border-bottom: 1px solid rgba(0, 0, 0, 0.125);\n"
                + "    }\n"
                + "\n"
                + "    .card-header:first-child {\n"
                + "      border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-header+.list-group .list-group-item:first-child {\n"
                + "      border-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-body {\n"
                + "      -ms-flex: 1 1 auto;\n"
                + "      flex: 1 1 auto;\n"
                + "      padding: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-title {\n"
                + "      margin-bottom: 0.75rem;\n"
                + "    }\n"
                + "\n"
                + "    .card>hr {\n"
                + "      margin-right: 0;\n"
                + "      margin-left: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card>.list-group:first-child .list-group-item:first-child {\n"
                + "      border-top-left-radius: 0.25rem;\n"
                + "      border-top-right-radius: 0.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card>.list-group:last-child .list-group-item:last-child {\n"
                + "      border-bottom-right-radius: 0.25rem;\n"
                + "      border-bottom-left-radius: 0.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-body {\n"
                + "      -ms-flex: 1 1 auto;\n"
                + "      flex: 1 1 auto;\n"
                + "      padding: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-title {\n"
                + "      margin-bottom: 0.75rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-subtitle {\n"
                + "      margin-top: -0.375rem;\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-text:last-child {\n"
                + "      margin-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-link:hover {\n"
                + "      text-decoration: none;\n"
                + "    }\n"
                + "\n"
                + "    .card-link+.card-link {\n"
                + "      margin-left: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-header {\n"
                + "      padding: 0.75rem 1.25rem;\n"
                + "      margin-bottom: 0;\n"
                + "      background-color: rgba(0, 0, 0, 0.03);\n"
                + "      border-bottom: 1px solid rgba(0, 0, 0, 0.125);\n"
                + "    }\n"
                + "\n"
                + "    .card-header:first-child {\n"
                + "      border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-header+.list-group .list-group-item:first-child {\n"
                + "      border-top: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-footer {\n"
                + "      padding: 0.75rem 1.25rem;\n"
                + "      background-color: rgba(0, 0, 0, 0.03);\n"
                + "      border-top: 1px solid rgba(0, 0, 0, 0.125);\n"
                + "    }\n"
                + "\n"
                + "    .card-footer:last-child {\n"
                + "      border-radius: 0 0 calc(0.25rem - 1px) calc(0.25rem - 1px);\n"
                + "    }\n"
                + "\n"
                + "    .card-header-tabs {\n"
                + "      margin-right: -0.625rem;\n"
                + "      margin-bottom: -0.75rem;\n"
                + "      margin-left: -0.625rem;\n"
                + "      border-bottom: 0;\n"
                + "    }\n"
                + "\n"
                + "    .card-header-pills {\n"
                + "      margin-right: -0.625rem;\n"
                + "      margin-left: -0.625rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-img-overlay {\n"
                + "      position: absolute;\n"
                + "      top: 0;\n"
                + "      right: 0;\n"
                + "      bottom: 0;\n"
                + "      left: 0;\n"
                + "      padding: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-img {\n"
                + "      width: 100%;\n"
                + "      border-radius: calc(0.25rem - 1px);\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card {\n"
                + "      overflow: hidden;\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card:not(:first-of-type) .card-header:first-child {\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card:not(:first-of-type):not(:last-of-type) {\n"
                + "      border-bottom: 0;\n"
                + "      border-radius: 0;\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card:first-of-type {\n"
                + "      border-bottom: 0;\n"
                + "      border-bottom-right-radius: 0;\n"
                + "      border-bottom-left-radius: 0;\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card:last-of-type {\n"
                + "      border-top-left-radius: 0;\n"
                + "      border-top-right-radius: 0;\n"
                + "    }\n"
                + "\n"
                + "    .accordion>.card .card-header {\n"
                + "      margin-bottom: -1px;\n"
                + "    }\n"
                + "\n"
                + "    .border-primary {\n"
                + "      border-color: #007bff !important;\n"
                + "    }\n"
                + "\n"
                + "    .border-secondary {\n"
                + "      border-color: #6c757d !important;\n"
                + "    }\n"
                + "\n"
                + "    .border-success {\n"
                + "      border-color: #28a745 !important;\n"
                + "    }\n"
                + "\n"
                + "\n"
                + "    .card-img-overlay {\n"
                + "      position: absolute;\n"
                + "      top: 0;\n"
                + "      right: 0;\n"
                + "      bottom: 0;\n"
                + "      left: 0;\n"
                + "      padding: 1.25rem;\n"
                + "    }\n"
                + "\n"
                + "    .card-img {\n"
                + "      width: 100%;\n"
                + "      border-radius: calc(0.25rem - 1px);\n"
                + "    }\n"
                + "\n"
                + "    .card-img-top {\n"
                + "      width: 100%;\n"
                + "      border-top-left-radius: calc(0.25rem - 1px);\n"
                + "      border-top-right-radius: calc(0.25rem - 1px);\n"
                + "    }\n"
                + "\n"
                + "    .card-img-bottom {\n"
                + "      width: 100%;\n"
                + "      border-bottom-right-radius: calc(0.25rem - 1px);\n"
                + "      border-bottom-left-radius: calc(0.25rem - 1px);\n"
                + "    }\n"
                + "\n"
                + "    .text-secondary {\n"
                + "      color: #6c757d !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-secondary:hover,\n"
                + "    a.text-secondary:focus {\n"
                + "      color: #494f54 !important;\n"
                + "    }\n"
                + "\n"
                + "    .text-success {\n"
                + "      color: #28a745 !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-success:hover,\n"
                + "    a.text-success:focus {\n"
                + "      color: #19692c !important;\n"
                + "    }\n"
                + "\n"
                + "    .text-info {\n"
                + "      color: #17a2b8 !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-info:hover,\n"
                + "    a.text-info:focus {\n"
                + "      color: #0f6674 !important;\n"
                + "    }\n"
                + "\n"
                + "    .text-warning {\n"
                + "      color: #ffc107 !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-warning:hover,\n"
                + "    a.text-warning:focus {\n"
                + "      color: #ba8b00 !important;\n"
                + "    }\n"
                + "\n"
                + "    .text-danger {\n"
                + "      color: #dc3545 !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-danger:hover,\n"
                + "    a.text-danger:focus {\n"
                + "      color: #a71d2a !important;\n"
                + "    }\n"
                + "\n"
                + "    .text-light {\n"
                + "      color: #f8f9fa !important;\n"
                + "    }\n"
                + "\n"
                + "    a.text-light:hover,\n"
                + "    a.text-light:focus {\n"
                + "      color: #cbd3da !important;\n"
                + "    }\n"
                + "  </style>\n"
                + "  <!-- <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\"> -->\n"
                + "\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <div class=\"container\">\n"
                + "\n"
                + "    <h3 class=\"text-center\">Portal EconoMundi Newsletter Diário</h3>\n"
                + "    <br><br>\n"
                + "    <h1 class=\"text-center\">LOGO</h1>\n"
                + "    <br>\n"
                + "    <div class=\"row word\">\n"
                + "\n"
                + "      <div class=\"card border-primary word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <div class=\"card-header\">" + wordList.get(0).getName() + "</div>\n"
                + "        <div class=\"card-body text-primary\">\n"
                + "\n"
                + "          <p class=\"card-text\">" + wordList.get(0).getDescription() + "</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"card border-secondary word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <div class=\"card-header\">" + wordList.get(1).getName() + "</div>\n"
                + "        <div class=\"card-body text-secondary\">\n"
                + "\n"
                + "          <p class=\"card-text\">" + wordList.get(1).getDescription() + "</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <div class=\"card-header\">" + wordList.get(2).getName() + "</div>\n"
                + "        <div class=\"card-body text-success\">\n"
                + "\n"
                + "          <p class=\"card-text\">" + wordList.get(2).getDescription() + "</p>\n"
                + "        </div>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "\n"
                + "    <br>\n"
                + "    <br>\n"
                + "    <h3 class=\"text-center\"> Notícias Brasil</h3>\n"
                + "    <div class=\"row word\">\n"
                + "\n"
                + "\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "             src=\"" + newsLetterBrazilList.get(0).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(0).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(0).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterBrazilList.get(1).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(1).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(1).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterBrazilList.get(2).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(2).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(2).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterBrazilList.get(3).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(3).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(3).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterBrazilList.get(5).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(4).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(4).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterBrazilList.get(5).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterBrazilList.get(5).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterBrazilList.get(5).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <br>\n"
                + "    <br>\n"
                + "    <h3 class=\"text-center\"> Notícias Mundo</h3>\n"
                + "    <div class=\"row word\">\n"
                + "\n"
                + "\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "             src=\"" + newsLetterWorldList.get(0).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(0).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(0).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterWorldList.get(1).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(1).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(1).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterWorldList.get(2).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(2).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(2).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterWorldList.get(3).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(3).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(3).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterWorldList.get(5).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(4).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(4).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "      <div class=\"card border-success word-card col-ld-4\" style=\"max-width: 18rem;\">\n"
                + "        <a href=\"#\" style=\"display:block;\">\n"
                + "          <img\n"
                + "            src=\"" + newsLetterWorldList.get(5).getUrl_image() + "\"\n"
                + "            class=\"card-img\" alt=\"...\">\n"
                + "          <div class=\"text-center \">" + newsLetterWorldList.get(5).getSource() + "</div>\n"
                + "          <div class=\"card-body text-info card-img-overlay\">\n"
                + "            <p class=\"card-text\">" + newsLetterWorldList.get(5).getTitle() + "</p>\n"
                + "          </div>\n"
                + "        </a>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "    <br>\n"
                + "    <br>\n"
                + "<br>\n"
                + "    <br>\n"
                + "    <h3 class=\"align-self-center text-center\"> Indices</h3>\n"
                + "    <div class=\"row word\">\n"
                + "    </div>"
                + "  </div>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

}
