/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.backend.economundi.payload;

import com.backend.economundi.database.dao.entity.NewsLetterDto;
import com.backend.economundi.database.dao.entity.UserEntity;
import com.backend.economundi.database.dao.entity.WordEntity;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 *
 * @author Alexandre
 */
@Component
public class EmailTemplates {

    public String getTemplateSign(String name) {
        String template = "<!DOCTYPE html\n"
                + "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "    <title>Economundi</title>\n"
                + "    <!-- Designed by https://github.com/kaytcat -->\n"
                + "    <!-- Robot header image designed by Freepik.com -->\n"
                + "\n"
                + "    <style type=\"text/css\">\n"
                + "        @import url(http://fonts.googleapis.com/css?family=Droid+Sans);\n"
                + "\n"
                + "        /* Take care of image borders and formatting */\n"
                + "\n"
                + "        img {\n"
                + "            max-width: 600px;\n"
                + "            outline: none;\n"
                + "            text-decoration: none;\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "            border: 0;\n"
                + "            outline: none;\n"
                + "            color: #bbbbbb;\n"
                + "        }\n"
                + "\n"
                + "        a img {\n"
                + "            border: none;\n"
                + "        }\n"
                + "\n"
                + "        /* General styling */\n"
                + "\n"
                + "        td,\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3 {\n"
                + "            font-family: Helvetica, Arial, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            -webkit-font-smoothing: antialiased;\n"
                + "            -webkit-text-size-adjust: none;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            color: #37302d;\n"
                + "            background: #ffffff;\n"
                + "            font-size: 16px;\n"
                + "        }\n"
                + "\n"
                + "        table {\n"
                + "            border-collapse: collapse !important;\n"
                + "        }\n"
                + "\n"
                + "        .headline {\n"
                + "            color: #ffffff;\n"
                + "            font-size: 36px;\n"
                + "        }\n"
                + "\n"
                + "        .force-full-width {\n"
                + "            width: 100% !important;\n"
                + "        }\n"
                + "\n"
                + "        .force-width-80 {\n"
                + "            width: 80% !important;\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"screen\">\n"
                + "        @media screen {\n"
                + "\n"
                + "            /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/\n"
                + "            td,\n"
                + "            h1,\n"
                + "            h2,\n"
                + "            h3 {\n"
                + "                font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"only screen and (max-width: 480px)\">\n"
                + "        /* Mobile styles */\n"
                + "        @media only screen and (max-width: 480px) {\n"
                + "\n"
                + "            table[class=\"w320\"] {\n"
                + "                width: 320px !important;\n"
                + "            }\n"
                + "\n"
                + "            td[class=\"mobile-block\"] {\n"
                + "                width: 100% !important;\n"
                + "                display: block !important;\n"
                + "            }\n"
                + "\n"
                + "\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"body\" style=\"padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\"\n"
                + "    bgcolor=\"#ffffff\">\n"
                + "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\" height=\"100%\">\n"
                + "        <tr>\n"
                + "            <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\" width=\"100%\">\n"
                + "                <center>\n"
                + "                    <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">\n"
                + "                        <tr>\n"
                + "                            <td align=\"center\" valign=\"top\">\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    style=\"margin:0 auto;\">\n"
                + "                                    <tr>\n"
                + "                                        <td style=\"font-size: 30px; text-align:center;\">\n"
                + "                                            Portal EconoMundi\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    bgcolor=\"#4dbfbf\">\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <br>\n"
                + "                                            <img src=\"https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf\"\n"
                + "                                                width=\"224\" height=\"240\" alt=\"robot picture\">\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td class=\"headline\">\n"
                + "                                            " + name + " Seu Cadastro Foi Realizado Com Sucesso!\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "\n"
                + "                                            <center>\n"
                + "                                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\"\n"
                + "                                                    width=\"60%\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td style=\"color:#187272;\">\n"
                + "                                                            <br>\n"
                + "                                                            Obrigado por se Cadastrar.\n"
                + "                                                            <br>\n"
                + "                                                            <br>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "                                            </center>\n"
                + "\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <div>\n"
                + "\n"
                + "                                                <a href=\"http://localhost:3000/noticias\"\n"
                + "                                                    style=\"background-color:#178f8f;border-radius:4px;color:#ffffff;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:50px;text-align:center;text-decoration:none;width:200px;-webkit-text-size-adjust:none;\">\n"
                + "                                                    Voltar ao Portal</a>\n"
                + "\n"
                + "                                            </div>\n"
                + "                                            <br>\n"
                + "                                            <br>\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "\n"
                + "\n"
                + "                            </td>\n"
                + "                        </tr>\n"
                + "                    </table>\n"
                + "                </center>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

    public String getTemplateRecovery(UserEntity user) {
        String template = "<!DOCTYPE html\n"
                + "    PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "\n"
                + "<head>\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "    <title>Economundi</title>\n"
                + "    <!-- Designed by https://github.com/kaytcat -->\n"
                + "    <!-- Robot header image designed by Freepik.com -->\n"
                + "\n"
                + "    <style type=\"text/css\">\n"
                + "        @import url(http://fonts.googleapis.com/css?family=Droid+Sans);\n"
                + "\n"
                + "        /* Take care of image borders and formatting */\n"
                + "\n"
                + "        img {\n"
                + "            max-width: 600px;\n"
                + "            outline: none;\n"
                + "            text-decoration: none;\n"
                + "            -ms-interpolation-mode: bicubic;\n"
                + "        }\n"
                + "\n"
                + "        a {\n"
                + "            text-decoration: none;\n"
                + "            border: 0;\n"
                + "            outline: none;\n"
                + "            color: #bbbbbb;\n"
                + "        }\n"
                + "\n"
                + "        a img {\n"
                + "            border: none;\n"
                + "        }\n"
                + "\n"
                + "        /* General styling */\n"
                + "\n"
                + "        td,\n"
                + "        h1,\n"
                + "        h2,\n"
                + "        h3 {\n"
                + "            font-family: Helvetica, Arial, sans-serif;\n"
                + "            font-weight: 400;\n"
                + "        }\n"
                + "\n"
                + "        td {\n"
                + "            text-align: center;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            -webkit-font-smoothing: antialiased;\n"
                + "            -webkit-text-size-adjust: none;\n"
                + "            width: 100%;\n"
                + "            height: 100%;\n"
                + "            color: #37302d;\n"
                + "            background: #ffffff;\n"
                + "            font-size: 16px;\n"
                + "        }\n"
                + "\n"
                + "        table {\n"
                + "            border-collapse: collapse !important;\n"
                + "        }\n"
                + "\n"
                + "        .headline {\n"
                + "            color: #ffffff;\n"
                + "            font-size: 36px;\n"
                + "        }\n"
                + "\n"
                + "        .force-full-width {\n"
                + "            width: 100% !important;\n"
                + "        }\n"
                + "\n"
                + "        .force-width-80 {\n"
                + "            width: 80% !important;\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"screen\">\n"
                + "        @media screen {\n"
                + "\n"
                + "            /*Thanks Outlook 2013! http://goo.gl/XLxpyl*/\n"
                + "            td,\n"
                + "            h1,\n"
                + "            h2,\n"
                + "            h3 {\n"
                + "                font-family: 'Droid Sans', 'Helvetica Neue', 'Arial', 'sans-serif' !important;\n"
                + "            }\n"
                + "        }\n"
                + "    </style>\n"
                + "\n"
                + "    <style type=\"text/css\" media=\"only screen and (max-width: 480px)\">\n"
                + "        /* Mobile styles */\n"
                + "        @media only screen and (max-width: 480px) {\n"
                + "\n"
                + "            table[class=\"w320\"] {\n"
                + "                width: 320px !important;\n"
                + "            }\n"
                + "\n"
                + "            td[class=\"mobile-block\"] {\n"
                + "                width: 100% !important;\n"
                + "                display: block !important;\n"
                + "            }\n"
                + "\n"
                + "\n"
                + "        }\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body class=\"body\" style=\"padding:0; margin:0; display:block; background:#ffffff; -webkit-text-size-adjust:none\"\n"
                + "    bgcolor=\"#ffffff\">\n"
                + "    <table align=\"center\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\" height=\"100%\">\n"
                + "        <tr>\n"
                + "            <td align=\"center\" valign=\"top\" bgcolor=\"#ffffff\" width=\"100%\">\n"
                + "                <center>\n"
                + "                    <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" class=\"w320\">\n"
                + "                        <tr>\n"
                + "                            <td align=\"center\" valign=\"top\">\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    style=\"margin:0 auto;\">\n"
                + "                                    <tr>\n"
                + "                                        <td style=\"font-size: 30px; text-align:center;\">\n"
                + "                                            Portal EconoMundi\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n"
                + "\n"
                + "                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\" class=\"force-full-width\"\n"
                + "                                    bgcolor=\"#4dbfbf\">\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <br>\n"
                + "                                            <img src=\"https://www.filepicker.io/api/file/TjmeNWS5Q2SFmtJlUGLf\"\n"
                + "                                                width=\"224\" height=\"240\" alt=\"robot picture\">\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td class=\"headline\">\n"
                + "                                            " + user.getFirst_name() + " Clique no Botão Abaixo para redefinir sua Senha!\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "\n"
                + "                                            <center>\n"
                + "                                                <table style=\"margin: 0 auto;\" cellpadding=\"0\" cellspacing=\"0\"\n"
                + "                                                    width=\"60%\">\n"
                + "                                                    <tr>\n"
                + "                                                        <td style=\"color:#187272;\">\n"
                + "                                                            <br>\n"
                + "                                                            você será redirecionado a página de redefinição de senha.\n"
                + "                                                            <br>\n"
                + "                                                            <br>\n"
                + "                                                        </td>\n"
                + "                                                    </tr>\n"
                + "                                                </table>\n"
                + "                                            </center>\n"
                + "\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                    <tr>\n"
                + "                                        <td>\n"
                + "                                            <div>\n"
                + "\n"
                + "                                                <a href=\"http://localhost:3000/recovery?" + user.getEmailVerificationToken() + "\"\n"
                + "                                                    style=\"background-color:#178f8f;border-radius:4px;color:#ffffff;display:inline-block;font-family:Helvetica, Arial, sans-serif;font-size:16px;font-weight:bold;line-height:50px;text-align:center;text-decoration:none;width:200px;-webkit-text-size-adjust:none;\">\n"
                + "                                                    Redefinir Senha</a>\n"
                + "\n"
                + "                                            </div>\n"
                + "                                            <br>\n"
                + "                                            <br>\n"
                + "                                        </td>\n"
                + "                                    </tr>\n"
                + "                                </table>\n" + "\n"
                + "\n"
                + "\n"
                + "                            </td>\n"
                + "                        </tr>\n"
                + "                    </table>\n"
                + "                </center>\n"
                + "            </td>\n"
                + "        </tr>\n"
                + "    </table>\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

    public String getNewsLetterTemplate(List<NewsLetterDto> newsLetterBrazilList, List<NewsLetterDto> newsLetterWorldList, List<WordEntity> wordList) {

        String url_word = "https://economundi-frontend.herokuapp.com/dicionario";
        String url_news = "https://economundi-frontend.herokuapp.com/noticias";

        String template = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "\n"
                + "<head>\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "    <style>\n"
                + "        :root {\n"
                + "            --blue: #007bff;\n"
                + "            --indigo: #6610f2;\n"
                + "            --purple: #6f42c1;\n"
                + "            --pink: #e83e8c;\n"
                + "            --red: #dc3545;\n"
                + "            --orange: #fd7e14;\n"
                + "            --yellow: #ffc107;\n"
                + "            --green: #28a745;\n"
                + "            --teal: #20c997;\n"
                + "            --cyan: #17a2b8;\n"
                + "            --white: #fff;\n"
                + "            --gray: #6c757d;\n"
                + "            --gray-dark: #343a40;\n"
                + "            --primary: #007bff;\n"
                + "            --secondary: #6c757d;\n"
                + "            --success: #28a745;\n"
                + "            --info: #17a2b8;\n"
                + "            --warning: #ffc107;\n"
                + "            --danger: #dc3545;\n"
                + "            --light: #f8f9fa;\n"
                + "            --dark: #343a40;\n"
                + "            --breakpoint-xs: 0;\n"
                + "            --breakpoint-sm: 576px;\n"
                + "            --breakpoint-md: 768px;\n"
                + "            --breakpoint-lg: 992px;\n"
                + "            --breakpoint-xl: 1200px;\n"
                + "            --font-family-sans-serif: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
                + "            --font-family-monospace: SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;\n"
                + "        }\n"
                + "\n"
                + "        *,\n"
                + "        *::before,\n"
                + "        *::after {\n"
                + "            box-sizing: border-box;\n"
                + "        }\n"
                + "\n"
                + "        html {\n"
                + "            font-family: sans-serif;\n"
                + "            line-height: 1.15;\n"
                + "            -webkit-text-size-adjust: 100%;\n"
                + "            -webkit-tap-highlight-color: rgba(0, 0, 0, 0);\n"
                + "        }\n"
                + "\n"
                + "        article,\n"
                + "        aside,\n"
                + "        figcaption,\n"
                + "        figure,\n"
                + "        footer,\n"
                + "        header,\n"
                + "        hgroup,\n"
                + "        main,\n"
                + "        nav,\n"
                + "        section {\n"
                + "            display: block;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            margin: 0;\n"
                + "            font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, \"Helvetica Neue\", Arial, \"Noto Sans\", sans-serif, \"Apple Color Emoji\", \"Segoe UI Emoji\", \"Segoe UI Symbol\", \"Noto Color Emoji\";\n"
                + "            font-size: 1rem;\n"
                + "            font-weight: 400;\n"
                + "            line-height: 1.5;\n"
                + "            color: #212529;\n"
                + "            text-align: left;\n"
                + "            background-color: #fff;\n"
                + "        }\n"
                + "\n"
                + "        [tabindex=\"-1\"]:focus {\n"
                + "            outline: 0 !important;\n"
                + "        }\n"
                + "\n"
                + "        * {\n"
                + "            box-sizing: border-box;\n"
                + "        }\n"
                + "\n"
                + "        body {\n"
                + "            background-color: #f1f1f1;\n"
                + "            padding: 20px;\n"
                + "            font-family: Arial;\n"
                + "        }\n"
                + "\n"
                + "        /* Center website */\n"
                + "        .main {\n"
                + "            max-width: 1000px;\n"
                + "            margin: auto;\n"
                + "        }\n"
                + "\n"
                + "        h1 {\n"
                + "            font-size: 50px;\n"
                + "            word-break: break-all;\n"
                + "        }\n"
                + "\n"
                + "        .row {\n"
                + "            margin: 8px -16px;\n"
                + "        }\n"
                + "\n"
                + "        /* Add padding BETWEEN each column */\n"
                + "        .row,\n"
                + "        .row>.column {\n"
                + "            padding: 8px;\n"
                + "        }\n"
                + "\n"
                + "        /* Create four equal columns that floats next to each other */\n"
                + "        .column {\n"
                + "            float: left;\n"
                + "            width: 25%;\n"
                + "        }\n"
                + "\n"
                + "        /* Clear floats after rows */\n"
                + "        .row:after {\n"
                + "            content: \"\";\n"
                + "            display: table;\n"
                + "            clear: both;\n"
                + "        }\n"
                + "\n"
                + "        /* Content */\n"
                + "        .content {\n"
                + "            background-color: white;\n"
                + "            padding: 10px;\n"
                + "            border-radius: 12px;\n"
                + "            border: 1px solid black;\n"
                + "            height: auto;\n"
                + "        }\n"
                + "\n"
                + "        /* Responsive layout - makes a two column-layout instead of four columns */\n"
                + "        @media screen and (max-width: 900px) {\n"
                + "            .column {\n"
                + "                width: 50%;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        /* Responsive layout - makes the two columns stack on top of each other instead of next to each other */\n"
                + "        @media screen and (max-width: 600px) {\n"
                + "            .column {\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "        }\n"
                + "\n"
                + "        .text-center {\n"
                + "            text-align: center !important;\n"
                + "        }\n"
                + "\n"
                + "        button {\n"
                + "            border-radius: 0;\n"
                + "        }\n"
                + "\n"
                + "        button:focus {\n"
                + "            outline: 1px dotted;\n"
                + "            outline: 5px auto -webkit-focus-ring-color;\n"
                + "        }\n"
                + "\n"
                + "        input,\n"
                + "        button,\n"
                + "        select,\n"
                + "        optgroup,\n"
                + "        textarea {\n"
                + "            margin: 0;\n"
                + "            font-family: inherit;\n"
                + "            font-size: inherit;\n"
                + "            line-height: inherit;\n"
                + "        }\n"
                + "\n"
                + "        button,\n"
                + "        input {\n"
                + "            overflow: visible;\n"
                + "        }\n"
                + "\n"
                + "        button,\n"
                + "        select {\n"
                + "            text-transform: none;\n"
                + "        }\n"
                + "\n"
                + "        select {\n"
                + "            word-wrap: normal;\n"
                + "        }\n"
                + "\n"
                + "        button,\n"
                + "        [type=\"button\"],\n"
                + "        [type=\"reset\"],\n"
                + "        [type=\"submit\"] {\n"
                + "            -webkit-appearance: button;\n"
                + "        }\n"
                + "\n"
                + "        button:not(:disabled),\n"
                + "        [type=\"button\"]:not(:disabled),\n"
                + "        [type=\"reset\"]:not(:disabled),\n"
                + "        [type=\"submit\"]:not(:disabled) {\n"
                + "            cursor: pointer;\n"
                + "        }\n"
                + "\n"
                + "        button::-moz-focus-inner,\n"
                + "        [type=\"button\"]::-moz-focus-inner,\n"
                + "        [type=\"reset\"]::-moz-focus-inner,\n"
                + "        [type=\"submit\"]::-moz-focus-inner {\n"
                + "            padding: 0;\n"
                + "            border-style: none;\n"
                + "        }\n"
                + "\n"
                + "        .align-self-center {\n"
                + "  -ms-flex-item-align: center !important;\n"
                + "  align-self: center !important;\n"
                + "}\n"
                + "    </style>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "\n"
                + "    <!-- MAIN (Center website) -->\n"
                + "    <div class=\"main\">\n"
                + "\n"
                + "        <h3 class=\"text-center\">Portal EconoMundi News</h3>\n"
                + "\n"
                + "        <h1 class=\"text-center\">LOGO</h1>\n"
                + "        <br>\n"
                + "        <!-- Palavras -->\n"
                + "        <div class=\"row\">\n"
                + "\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <h3 class=\"text-center\">" + wordList.get(0).getName() + "</h3>\n"
                + "                    <p>" + wordList.get(0).getDescription() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <h3 class=\"text-center\">" + wordList.get(1).getName() + "</h3>\n"
                + "                    <p>" + wordList.get(1).getDescription() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <h3 class=\"text-center\">" + wordList.get(2).getName() + "</h3>\n"
                + "                    <p>" + wordList.get(2).getDescription() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <h3 class=\"text-center\">" + wordList.get(3).getName() + "</h3>\n"
                + "                    <p>" + wordList.get(3).getDescription() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "\n"
                + "\n"
                + "            <!-- END GRID -->\n"
                + "        </div>\n"
                + "        <!-- Fim das Palavras -->\n"
                + "<br><br>\n"
                + "        <button onclick=\"" + url_word + "\" style=\"position:relative; align-content: center;\">Saiba Mais</button>\n"
                + "        <!-- Noticias Brasil-->\n"
                + "        <h3 class=\"text-center\"> Notícias Brasil</h3>\n"
                + "        <div class=\"content\">\n"
                + "            <img src=\"" + newsLetterBrazilList.get(0).getUrl_image() + "\"\n"
                + "                alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "            <a href=\"" + newsLetterBrazilList.get(0).getUrl_news() + "\">\n"
                + "                <h3>" + newsLetterBrazilList.get(0).getSource() + "</h3>\n"
                + "            </a>\n"
                + "            <p>" + newsLetterBrazilList.get(0).getTitle() + "</p>\n"
                + "        </div>\n"
                + "\n"
                + "\n"
                + "        <div class=\"row\">\n"
                + "\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <img src=\"" + newsLetterBrazilList.get(1).getUrl_image() + "\"\n"
                + "                        alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterBrazilList.get(1).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterBrazilList.get(1).getSource() + "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterBrazilList.get(1).getTitle() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <img src=\"" + newsLetterBrazilList.get(2).getUrl_image() + "\"\n"
                + "                        alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterBrazilList.get(2).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterBrazilList.get(2).getSource() + "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterBrazilList.get(2).getTitle() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <img src=\"" + newsLetterBrazilList.get(3).getUrl_image() + "\"\n"
                + "                        alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterBrazilList.get(3).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterBrazilList.get(3).getSource() + "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterBrazilList.get(2).getTitle() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "                    <img src=\"" + newsLetterBrazilList.get(4).getUrl_image() + "\"\n"
                + "                        alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterBrazilList.get(4).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterBrazilList.get(4).getSource() + "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterBrazilList.get(4).getTitle() + "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "\n"
                + "        </div>\n"
                + "        <button onclick=\"" + url_news + "\" style=\"position:relative; align-content: center;\">Mais Notícias Sobre o Brasil</button>\n"
                + "        <!-- Fim noticias Brasil -->\n"
                + "        <!-- Noticias Mundo-->\n"
                + "        <h3 class=\"text-center\"> Notícias Mundo</h3>\n"
                + "        <div class=\"content\">\n"
                + "           <img src=\"" + newsLetterWorldList.get(0).getUrl_image() + "\"\n"
                + "                alt=\"EconoMundi\" style=\"width:100%\">\n"
                + "            <a href=\"" + newsLetterWorldList.get(0).getUrl_news() + "\">\n"
                + "                <h3>" + newsLetterWorldList.get(0).getSource()+ "</h3>\n"
                + "            </a>\n"
                + "            <p>" + newsLetterWorldList.get(0).getTitle()+ "</p>\n"
                + "        </div>\n"
                + "\n"
                + "\n"
                + "        <div class=\"row\">\n"
                + "\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "           <img src=\"" + newsLetterWorldList.get(1).getUrl_image() + "\"\n" + "                        alt=\"Mountains\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterWorldList.get(1).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterWorldList.get(1).getSource()+ "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterWorldList.get(1).getTitle()+ "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "           <img src=\"" + newsLetterWorldList.get(2).getUrl_image() + "\"\n" + "                        alt=\"Mountains\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterWorldList.get(2).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterWorldList.get(2).getSource()+ "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterWorldList.get(2).getTitle()+ "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "           <img src=\"" + newsLetterWorldList.get(3).getUrl_image() + "\"\n" + "                        alt=\"Mountains\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterWorldList.get(3).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterWorldList.get(3).getSource()+ "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterWorldList.get(3).getTitle()+ "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "\n"
                + "            <div class=\"column\">\n"
                + "                <div class=\"content\">\n"
                + "           <img src=\"" + newsLetterWorldList.get(4).getUrl_image() + "\"\n" + "                        alt=\"Mountains\" style=\"width:100%\">\n"
                + "                    <a href=\"" + newsLetterWorldList.get(4).getUrl_news() + "\">\n"
                + "                        <h3>" + newsLetterWorldList.get(4).getSource()+ "</h3>\n"
                + "                    </a>\n"
                + "                    <p>" + newsLetterWorldList.get(4).getTitle()+ "</p>\n"
                + "                </div>\n"
                + "            </div>\n"
                + "\n"
                + "        </div>\n"
                + "        <button style=\"position:relative; align-content: center;\">Mais Notícias Sobre o Mundo</button>\n"
                + "        <!-- Fim noticias Mundo -->\n"
                + "    </div>\n"
                + "\n"
                + "</body>\n"
                + "\n"
                + "</html>";

        return template;
    }

}
